services:
  grabvidzilla-cli:
    image: grabvidzilla:latest
    build: .
    container_name: grabvidzilla-cli
    stdin_open: true
    tty: true
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./Downloads:/app/Downloads
      - ./tools:/app/tools
    networks:
      - grabvidzilla-net

  grabvidzilla-ui:
    image: grabvidzilla:latest
    build: .
    container_name: grabvidzilla-ui
    working_dir: /app
    entrypoint: ["streamlit"]
    command:
      - run
      - ui/ui_app.py
      - --server.address=0.0.0.0
      - --server.port=8501
    environment:
      - HOME=/app
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      - ./Downloads:/app/Downloads
      - ./tools:/app/tools
    networks:
      - grabvidzilla-net

  grabvidzilla-api:
    image: grabvidzilla:latest
    build: .
    container_name: grabvidzilla-api
    working_dir: /app
    entrypoint: ["uvicorn"]
    command:
      - api.api_main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    environment:
      - HOME=/app
      - DOWNLOADS_DIR=/app/Downloads
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./Downloads:/app/Downloads
      - ./tools:/app/tools
    networks:
      - grabvidzilla-net

networks:
  grabvidzilla-net:
    driver: bridge
